version: "3"
services:
  servicebackend:
    container_name: seiwhale-backend
    build:
      dockerfile: Dockerfile.dev
      context: ./services/server
    volumes:
      - /app/node_modules
      - ./services/server:/app
  servicefrontend:
    container_name: seiwhale-frontend
    build:
      dockerfile: Dockerfile.dev
      context: ./services/webapp
    volumes:
      - /app/node_modules
      - ./services/webapp:/app
  serviceredis:
    container_name: seiwhale-redis
    image: "redis"
  nginx:
    container_name: seiwhale-nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    ports:
      - "7070:80"